# Basic configuration template for SQL exporter.
databases:
  - address:
    user:
    password: 
    name:
    metrics:
      - statement:
        interval:
        name:
        help:
        labels:
